FROM python:3

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY tests ./tests
COPY custom_components/bluetti_modbus ./custom_components/bluetti_modbus

RUN python3 -m unittest discover -s tests -p "*.py"
